include:
  - compose-system.yml
  - compose-dashboard.yml
  - compose-monitor.yml
  - compose-tools.yml
  - compose-dev.yml
  - compose-secrets.yml
  - compose-smarthome.yml
  - compose-knowledge.yml
  - compose-productivity.yml
  - compose-media.yml
  - compose-irl.yml
  - compose-chat.yml

networks:
  homelab_net:
    name: homelab_net
    external: true
