#!/usr/bin/env bash
# glance-gen.sh — write Glance config with widgets + auto-discovery.
#
# Glance's `docker-containers` widget reads `glance.*` (or fallback
# `homepage.*`) container labels live via the docker socket, so no per-container
# enumeration is needed here — just provide static widgets (clock, search,
# resources, calendar, bookmarks) and let the docker widget discover the rest.
#
# Idempotent — overwrites /app/config/glance.yml each run.
#
# Usage: invoked automatically by `glance-init` on container startup.
# Manual: ./scripts/glance-gen.sh [output-path]

set -eu

OUT="${1:-/app/config/glance.yml}"
DOMAIN="${DUCKDNS_DOMAIN:-localhost}"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
---
# Auto-generated by glance-gen.sh.
# DO NOT EDIT — re-run glance-gen.sh to regenerate.
# Customize compose labels (homepage.* or glance.*) to control the
# docker-containers widget below. Container icon/name/description/url
# are pulled live from those labels via the docker socket.

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: clock
            options:
              hour-format: 24h
          - type: resources
          - type: search
            options:
              search-engine: https://search.${DOMAIN}/search?q=
              placeholder: Search via SearXNG…
          - type: calendar
      - size: full
        widgets:
          - type: bookmarks
            title: Bookmarks
            groups:
              - title: flat-lab
                links:
                  - title: Homepage dashboard
                    url: https://dash.${DOMAIN}
                  - title: Glance
                    url: https://glance.${DOMAIN}
                  - title: SearXNG
                    url: https://search.${DOMAIN}
                  - title: AdGuard
                    url: https://adguard.${DOMAIN}
                  - title: Uptime Kuma
                    url: https://status.${DOMAIN}
              - title: Proton (privacy suite)
                links:
                  - title: Proton Mail
                    url: https://mail.proton.me
                    icon: https://proton.me/favicon.ico
                  - title: Proton Calendar
                    url: https://calendar.proton.me
                    icon: https://proton.me/favicon.ico
                  - title: Proton Drive
                    url: https://drive.proton.me
                    icon: https://proton.me/favicon.ico
                  - title: Proton Pass
                    url: https://pass.proton.me
                    icon: https://proton.me/favicon.ico
                  - title: Proton VPN
                    url: https://protonvpn.com
                    icon: https://proton.me/favicon.ico
              - title: Operator essentials
                links:
                  - title: GitHub
                    url: https://github.com
                  - title: HackMD
                    url: https://hackmd.io
                  - title: ProtonMail
                    url: https://account.proton.me
          - type: docker-containers
            options:
              title: Services
              running-only: true
              hide-by-default: false
              sort: name
EOF

echo "[glance-gen] wrote $OUT"
